### PR TITLE
Gui

### PR DESCRIPTION
**Pull request by Leah2356**
Screen Shot 2024-03-20 at 6 19 48 PM

### CODE REVIEW

**Comment by andrewoid** [comment]
Add a screenshot

**Comment by Leah2356** [comment]
It's not working, do you know what might be wrong with it?

**Comment by andrewoid** [comment]
> It's not working, do you know what might be wrong with it?

What does "not working" mean?

**Comment by Leah2356** [comment]
When I run main this comes up:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException:
Cannot read the array length because "this.field" is null
at feiner.fallingsand.SandComponent.paintComponent(SandComponent.java:20)
at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
at
java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5325)
at
java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
at
java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
at
java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
at java.desktop/javax.swing.JComponent.paint(JComponent.java:1114)
at
java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
at
java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
at
java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
at java.desktop/java.awt.Container.paint(Container.java:2005)
at java.desktop/java.awt.Window.paint(Window.java:3959)
at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:889)
at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
at
java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at
java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
at
java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
at
java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
at
java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
at
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
at
java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by andrewoid** [comment]
> java.lang.NullPointerException: Cannot read the array length because "this.field" is null at feiner.fallingsand.SandComponent.paintComponent(SandComponent.java:20)

The error and the line number is right there.

**Comment by Leah2356** [comment]
I fixed it. The output is still not showing up. Do you possibly know why that would be?

**Comment by andrewoid** [comment]
> I fixed it. The output is still not showing up. Do you possibly know why that would be?

I don't. But I do know that you have a failing test.

**Comment by Leah2356** [comment]
I fixed the tests.

**Comment by andrewoid** [comment]
Add a screenshot

**Comment by Leah2356** [comment]
The output is still not working.

**Comment by Leah2356** [comment]
Would you be able to help me with it please?

**Comment by andrewoid** [comment]
There are no more errors in the logs?

**Comment by Leah2356** [comment]
No

**Review by andrewoid — APPROVED** [review]

**Pull request merged**
